# Generated by Django 4.2 on 2023-04-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarix', models.DateField(auto_created=True, verbose_name='tarix')),
                ('title', models.CharField(max_length=200, verbose_name='Basliq')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Sekil')),
                ('metn', models.TextField(max_length=500, verbose_name='metn')),
            ],
        ),
    ]
